import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Head from "next/head"
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillWechat, AiFillInstagram, AiOutlineWhatsApp, AiOutlineMail, AiOutlineGithub} from 'react-icons/ai'
import Image from "next/image";
import deved from '../fotos/foto_perfil.png';
import {useState} from "react";
import React from 'react';




export default function Home() {
  const [darkMode, setdarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>João Teixeira Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/background.ico" />
      </Head>
      <main className="bg-gray-300 dark:bg-gray-600 px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-end">
            <ul className="flex items-center dark:text-white">
                <li><BsFillMoonStarsFill onClick={() => setdarkMode(!darkMode)} className="cursor-pointer text-2xl"/></li>
                <li><a className="bg-gray-400 dark:text-black px-4 py-2 rounded-md ml-8"  href="/CV.pdf" download>Download CV</a></li>
            </ul>
          </nav> 
            <div className="xl:flex xl:justify-between">  

              <div className="text-center xl:text-left p-10 xl:max-w-3xl">
                <h2 className="text-5xl py-2 text-yellow-900 "> João Teixeira </h2>
                <h3 className="text-2xl py-2 dark:text-white "> Developer </h3>
                <p className="text-md py-5 leading-8 text-gray-800 dark:text-white " >
                  Olá, neste website encontra o meu CV no canto superior direito como também 
                algumas das competencias que fui adquirindo ao longo do meu curso. Encontra também
                várias formas de me contactar e 
                esteja á vontade para me contactar.
                  Mais a baixo encontra, as linguagens de programação com quais eu já trabalhei, econtra 
                também as frameworks, databases e as tools.
                  Agradeço pelo contacto
                </p>
              </div>

              <div className=" relative mx-auto w-80 h-80">
                <Image src={deved} alt="foto_perfil" className="  rounded-full  w-80 h-80 "/>
              </div> 
            </div> 
          <div className="text-5xl ">
            <ul className="dark:text-white">
                <li className="flex flex-row justify-center">
                  <div className="p-5">
                  <a href="https://www.linkedin.com/in/jo%C3%A3o-teixeira-037773228/"><AiFillLinkedin/></a>
                  </div>
                  <div className="p-5">
                    <a href="https://wa.me/351916762457"><AiOutlineWhatsApp/></a>
                  </div>
                  <div className="p-5">
                    <a href="mailto:jjoao.business@gmail.com"><AiOutlineMail/></a>
                    </div>
                  <div className="p-5">
                    <a href="https://github.com/joaoteixeira03"><AiOutlineGithub/></a>
                  </div>
                </li>
            </ul>
          </div>
          <div className="flex justify-end py-5 dark:text-white">
            <h3>Desenvolvido por João Teixeira</h3>
          </div>

          <div className='text-center'>
            <h2 className='text-2xl mt-40  text-blue-500 dark:text-blue-500'>Programing Languages</h2>
            <div className="flex flex-col md:flex-row items-center justify-center">
              <Image src="/logos/c.svg" alt="Icons" width={80} height={80} className='m-3' />
              <Image src="/logos/css.svg" alt="Icons" width={80} height={80} className='m-3' />
              <Image src="/logos/html5.svg" alt="Icons" width={100} height={100} className='m-3' />
              <Image src="/logos/java.svg" alt="Icons" width={80} height={80} className='m-3' />
              <Image src="/logos/javascript.svg" alt="Icons" width={80} height={80} className='m-3' />
              <Image src="/logos/python.svg" alt="Icons" width={80} height={80} className='m-3' />
              <Image src="/logos/typescript.svg" alt="Icons" width={80} height={80} className='m-3' />
            </div>
            <h2 className='text-2xl mt-32  text-blue-500 dark:text-blue-500'>Frameworks</h2>
            <div className="flex flex-col md:flex-row items-center justify-center">
              <Image src="/logos/next_js.svg" alt="Icons" width={100} height={100} className='m-3' />
              <Image src="/logos/nodejs.svg" alt="Icons" width={100} height={100} className='m-3' />
              <Image src="/logos/react.svg" alt="Icons" width={80} height={80} className='m-3' />             
            </div>
            <h2 className='text-2xl mt-32  text-blue-500 dark:text-blue-500'>Databases</h2>
            <div className="flex flex-col md:flex-row items-center justify-center">
              <Image src="/logos/microsoft_sql_server.svg" alt="Icons" width={120} height={120} className='m-3' />
              <Image src="/logos/mysql.svg" alt="Icons" width={100} height={100} className='m-3' />            
            </div>
            <h2 className='text-2xl mt-32  text-blue-500 dark:text-blue-500'>Tools</h2>
            <div className="flex flex-col md:flex-row items-center justify-center">
              <Image src="/logos/adobe_illustrator.svg" alt="Icons" width={80} height={80} className='m-3' />
              <Image src="/logos/eclipse.svg" alt="Icons" width={80} height={80} className='m-3' /> 
              <Image src="/logos/intellij.svg" alt="Icons" width={80} height={80} className='m-3' />  
              <Image src="/logos/pycharm.svg" alt="Icons" width={80} height={80} className='m-3' />  
              <Image src="/logos/visual_studio_code.svg" alt="Icons" width={80} height={80} className='m-3' />     
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}




